// <auto-generated />
using System;
using MealPrep.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealPrep.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealPrep.DAL.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("full_name");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.DeliveryOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<int?>("DeliverySlotId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_slot_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_delivery_orders");

                    b.HasIndex("DeliverySlotId")
                        .HasDatabaseName("ix_delivery_orders_delivery_slot_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_delivery_orders_subscription_id");

                    b.ToTable("delivery_orders", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.DeliveryOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_order_id");

                    b.Property<int?>("MealId")
                        .HasColumnType("integer")
                        .HasColumnName("meal_id");

                    b.Property<string>("MealNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("meal_name_snapshot");

                    b.Property<string>("MealType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("meal_type");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_delivery_order_items");

                    b.HasIndex("DeliveryOrderId")
                        .HasDatabaseName("ix_delivery_order_items_delivery_order_id");

                    b.HasIndex("MealId")
                        .HasDatabaseName("ix_delivery_order_items_meal_id");

                    b.ToTable("delivery_order_items", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.DeliverySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_delivery_slots");

                    b.ToTable("delivery_slots", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<int>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<decimal>("Carbs")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("carbs");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<decimal>("Fat")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fat");

                    b.PrimitiveCollection<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("images");

                    b.PrimitiveCollection<string[]>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ingredients");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Protein")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("protein");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_meals");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.NutritionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("customer_email");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("MealId")
                        .HasColumnType("integer")
                        .HasColumnName("meal_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_nutrition_logs");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("ix_nutrition_logs_app_user_id");

                    b.HasIndex("MealId")
                        .HasDatabaseName("ix_nutrition_logs_meal_id");

                    b.ToTable("nutrition_logs", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliverySlotId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_slot_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("ix_orders_app_user_id");

                    b.HasIndex("DeliverySlotId")
                        .HasDatabaseName("ix_orders_delivery_slot_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_orders_subscription_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MealId")
                        .HasColumnType("integer")
                        .HasColumnName("meal_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("MealId")
                        .HasDatabaseName("ix_order_items_meal_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.HasKey("Id")
                        .HasName("pk_otp_codes");

                    b.ToTable("otp_codes", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("ix_payments_app_user_id");

                    b.HasIndex("PaymentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_payment_code");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_payments_subscription_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gateway");

                    b.Property<string>("OrderId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("order_id");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("text")
                        .HasColumnName("raw_response_json");

                    b.Property<string>("RequestId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("response_code");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("response_message");

                    b.HasKey("Id")
                        .HasName("pk_payment_transactions");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_payment_transactions_payment_id");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_name");

                    b.ToTable("plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 300000m,
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói đăng ký theo tuần (7 ngày)",
                            DurationDays = 7,
                            IsActive = true,
                            Name = "Weekly"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 1000000m,
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói đăng ký theo tháng (30 ngày)",
                            DurationDays = 30,
                            IsActive = true,
                            Name = "Monthly"
                        });
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.PlanMealTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("ExtraPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("extra_price");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("meals_per_day");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.HasKey("Id")
                        .HasName("pk_plan_meal_tiers");

                    b.HasIndex("PlanId", "MealsPerDay")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_meal_tiers_plan_id_meals_per_day");

                    b.ToTable("plan_meal_tiers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 0m,
                            IsActive = true,
                            MealsPerDay = 1,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 150000m,
                            IsActive = true,
                            MealsPerDay = 2,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 280000m,
                            IsActive = true,
                            MealsPerDay = 3,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 0m,
                            IsActive = true,
                            MealsPerDay = 1,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 500000m,
                            IsActive = true,
                            MealsPerDay = 2,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 900000m,
                            IsActive = true,
                            MealsPerDay = 3,
                            PlanId = 2
                        });
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("customer_name");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("meals_per_day");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("ix_subscriptions_app_user_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscriptions_plan_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.UserAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllergyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("allergy_name");

                    b.Property<int>("UserNutritionProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("user_nutrition_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_user_allergies");

                    b.HasIndex("UserNutritionProfileId")
                        .HasDatabaseName("ix_user_allergies_user_nutrition_profile_id");

                    b.ToTable("user_allergies", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.UserDislikedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<int>("MealId")
                        .HasColumnType("integer")
                        .HasColumnName("meal_id");

                    b.HasKey("Id")
                        .HasName("pk_user_disliked_meals");

                    b.HasIndex("MealId")
                        .HasDatabaseName("ix_user_disliked_meals_meal_id");

                    b.HasIndex("AppUserId", "MealId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_disliked_meals_app_user_id_meal_id");

                    b.ToTable("user_disliked_meals", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.UserNutritionProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("activity_level");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<int>("DietPreference")
                        .HasColumnType("integer")
                        .HasColumnName("diet_preference");

                    b.Property<int>("Goal")
                        .HasColumnType("integer")
                        .HasColumnName("goal");

                    b.Property<int>("HeightCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_cm");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("meals_per_day");

                    b.Property<string>("Notes")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_user_nutrition_profiles");

                    b.HasIndex("AppUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_nutrition_profiles_app_user_id");

                    b.ToTable("user_nutrition_profiles", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.WeeklyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date")
                        .HasColumnName("week_end");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id")
                        .HasName("pk_weekly_menus");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_weekly_menus_created_by_user_id");

                    b.ToTable("weekly_menus", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.WeeklyMenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("MealId")
                        .HasColumnType("integer")
                        .HasColumnName("meal_id");

                    b.Property<int>("WeeklyMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_menu_id");

                    b.HasKey("Id")
                        .HasName("pk_weekly_menu_items");

                    b.HasIndex("MealId")
                        .HasDatabaseName("ix_weekly_menu_items_meal_id");

                    b.HasIndex("WeeklyMenuId")
                        .HasDatabaseName("ix_weekly_menu_items_weekly_menu_id");

                    b.ToTable("weekly_menu_items", (string)null);
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.AppUser", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.DeliveryOrder", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.DeliverySlot", "DeliverySlot")
                        .WithMany()
                        .HasForeignKey("DeliverySlotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_delivery_orders_delivery_slots_delivery_slot_id");

                    b.HasOne("MealPrep.DAL.Entities.Subscription", "Subscription")
                        .WithMany("DeliveryOrders")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_orders_subscriptions_subscription_id");

                    b.Navigation("DeliverySlot");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.DeliveryOrderItem", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.DeliveryOrder", "DeliveryOrder")
                        .WithMany("Items")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_order_items_delivery_orders_delivery_order_id");

                    b.HasOne("MealPrep.DAL.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_delivery_order_items_meals_meal_id");

                    b.Navigation("DeliveryOrder");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.NutritionLog", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.AppUser", "AppUser")
                        .WithMany("NutritionLogs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nutrition_logs_users_app_user_id");

                    b.HasOne("MealPrep.DAL.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nutrition_logs_meals_meal_id");

                    b.Navigation("AppUser");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Order", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_app_user_id");

                    b.HasOne("MealPrep.DAL.Entities.DeliverySlot", "DeliverySlot")
                        .WithMany()
                        .HasForeignKey("DeliverySlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_delivery_slots_delivery_slot_id");

                    b.HasOne("MealPrep.DAL.Entities.Subscription", "Subscription")
                        .WithMany("Orders")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_subscriptions_subscription_id");

                    b.Navigation("AppUser");

                    b.Navigation("DeliverySlot");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_meals_meal_id");

                    b.HasOne("MealPrep.DAL.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Meal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Payment", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_app_user_id");

                    b.HasOne("MealPrep.DAL.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_subscriptions_subscription_id");

                    b.Navigation("AppUser");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_transactions_payments_payment_id");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.PlanMealTier", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.Plan", "Plan")
                        .WithMany("MealTiers")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_meal_tiers_plans_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Subscription", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.AppUser", "AppUser")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_app_user_id");

                    b.HasOne("MealPrep.DAL.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_plans_plan_id");

                    b.Navigation("AppUser");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.UserAllergy", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.UserNutritionProfile", "UserNutritionProfile")
                        .WithMany("Allergies")
                        .HasForeignKey("UserNutritionProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_allergies_user_nutrition_profiles_user_nutrition_profi");

                    b.Navigation("UserNutritionProfile");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.UserDislikedMeal", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.AppUser", "AppUser")
                        .WithMany("DislikedMeals")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_disliked_meals_users_app_user_id");

                    b.HasOne("MealPrep.DAL.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_disliked_meals_meals_meal_id");

                    b.Navigation("AppUser");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.UserNutritionProfile", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.AppUser", "AppUser")
                        .WithOne("NutritionProfile")
                        .HasForeignKey("MealPrep.DAL.Entities.UserNutritionProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_nutrition_profiles_users_app_user_id");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.WeeklyMenu", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.AppUser", "CreatedBy")
                        .WithMany("WeeklyMenus")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_weekly_menus_users_created_by_user_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.WeeklyMenuItem", b =>
                {
                    b.HasOne("MealPrep.DAL.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_menu_items_meals_meal_id");

                    b.HasOne("MealPrep.DAL.Entities.WeeklyMenu", "WeeklyMenu")
                        .WithMany("Items")
                        .HasForeignKey("WeeklyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_menu_items_weekly_menus_weekly_menu_id");

                    b.Navigation("Meal");

                    b.Navigation("WeeklyMenu");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.AppRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.AppUser", b =>
                {
                    b.Navigation("DislikedMeals");

                    b.Navigation("NutritionLogs");

                    b.Navigation("NutritionProfile");

                    b.Navigation("Orders");

                    b.Navigation("Subscriptions");

                    b.Navigation("WeeklyMenus");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.DeliveryOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Plan", b =>
                {
                    b.Navigation("MealTiers");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.Subscription", b =>
                {
                    b.Navigation("DeliveryOrders");

                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.UserNutritionProfile", b =>
                {
                    b.Navigation("Allergies");
                });

            modelBuilder.Entity("MealPrep.DAL.Entities.WeeklyMenu", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
